# Generated by Django 4.1 on 2022-08-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'verbose_name': 'Клиента', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AddField(
            model_name='table',
            name='service',
            field=models.CharField(blank=True, max_length=30, verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='table',
            name='last_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='table',
            name='money',
            field=models.IntegerField(null=True, verbose_name='Стоимость услуги'),
        ),
        migrations.AlterField(
            model_name='table',
            name='month',
            field=models.CharField(blank=True, max_length=20, verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(blank=True, max_length=20, verbose_name='Имя'),
        ),
    ]
