# Generated by Django 4.1 on 2022-08-18 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('money', models.IntegerField(verbose_name='Стоимость услуги')),
                ('month', models.CharField(max_length=20, verbose_name='Месяц')),
            ],
        ),
    ]
